### ISSUE TITLE
shows command not found

### ISSUE THREAD

**Issue by ginhiki** [Nudin/mplug#6]
I use arch and installed it via pip, when i try running the command mplug install plugin_name, it shows command not found. How to fix this?

**Comment by Nudin** [comment]
Probably you got a warning like this on installation:
```
  WARNING: The script mplug is installed in '/home/michi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

To fix this you can either edit the PATH environment variable or call the file directly. Try running `pip uninstall  mplug` but enter 'n' to abort the uninstallation. It should look like this:
```
$ pip uninstall  mplug
Found existing installation: mplug 0.2.1
Uninstalling mplug-0.2.1:
  Would remove:
    /home/michi/.local/bin/mplug
    /home/michi/.local/lib/python3.8/site-packages/mplug-0.2.1.dist-info/*
    /home/michi/.local/lib/python3.8/site-packages/mplug/*
Proceed (y/n)? n
```
Then you know the file is at `/home/michi/.local/bin/mplug` (in my case). You can then run it directly `home/michi/.local/bin/mplug install someting` or add the path `/home/michi/.local/bin/` to PATH (how to do that depends on your operating system).
